### ISSUE TITLE
uninitialized constant Mods (NameError)

### ISSUE THREAD

**Issue by atz** [sul-dlss/stanford-mods#23]
Basic require (intended to be supported) fails with error.  Reproduced in new branch `require_deps`.
    
Error is:
```bash
$ rspec rspec/searchworks_basic_spec.rb 
/Users/atz/repos/stanford-mods/lib/stanford-mods/searchworks.rb:8:in `<module:Mods>': uninitialized constant Mods (NameError)
	from /Users/atz/repos/stanford-mods/lib/stanford-mods/searchworks.rb:6:in `<module:Stanford>'
	from /Users/atz/repos/stanford-mods/lib/stanford-mods/searchworks.rb:5:in `<top (required)>'
	from /Users/atz/repos/stanford-mods/spec/searchworks_basic_spec.rb:3:in `require'
	from /Users/atz/repos/stanford-mods/spec/searchworks_basic_spec.rb:3:in `<top (required)>'
	from /Users/atz/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `load'
	from /Users/atz/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `block in load_spec_files'
	from /Users/atz/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `each'
	from /Users/atz/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `load_spec_files'
	from /Users/atz/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:96:in `setup'
	from /Users/atz/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:84:in `run'
	from /Users/atz/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:69:in `run'
	from /Users/atz/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:37:in `invoke'
	from /Users/atz/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.1.7/exe/rspec:4:in `<top (required)>'
	from /Users/atz/.rvm/gems/ruby-2.1.2/bin/rspec:23:in `load'
	from /Users/atz/.rvm/gems/ruby-2.1.2/bin/rspec:23:in `<main>'
	from /Users/atz/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/atz/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```
    
Probably need to "require 'Mods'" in searchworks.rb.
Alternatively, extend stanford_mods.rb or something that already requires it.

**Comment by ndushay** [comment]
@lmcglohon @cbeer
